### ISSUE TITLE
Installation without composer

### ISSUE THREAD

**Issue by Pierroda** [woothee/woothee-php#29]
Dears,

Is there a way to install woothee-php without Composer. My web hoster doesn't enable me to do so.

Thanks in advace for your help.

**Comment by yuya-takeyama** [comment]
@Pierroda 
In my understanding, Composer doesn't require administrator authorization.
So you can just download composer.phar and install with it.

ref: https://getcomposer.org/download/

```
$ curl -sS https://getcomposer.org/installer | php
$ php composer.phar require woothee/woothee
```

**Comment by yuya-takeyama** [comment]
>Is there a way to install woothee-php without Composer.

And we don't have any plant to provide it.

**Comment by Pierroda** [comment]
Thanks for your input.

**Comment by yuya-takeyama** [comment]
Let me close for now.
