### ISSUE TITLE
Follow woothee 1.10

### ISSUE THREAD

**Issue by zonuexe** [woothee/woothee-php#45]
I want to follow [woothee v1.10](https://github.com/woothee/woothee/commit/1d21d7cbfd57b568e964cdd2ef98f9e046512628)

**Comment by zonuexe** [comment]
refs https://github.com/woothee/woothee/issues/51

**Comment by zonuexe** [comment]
Woothee-PHP tests now do not work with PHP 7.3, so I updated the dependencies in https://github.com/woothee/woothee-php/pull/44 .

**Comment by zonuexe** [comment]
Merged https://github.com/woothee/woothee-php/pull/48

**Comment by okonomi** [comment]
v1.10.0 released!
https://github.com/woothee/woothee-php/releases/tag/v1.10.0
